export enum WALLET_TYPE {
    BTC='BTC', ETH='ETH'
}

export enum SIDE {
    SELL='SELL', BUY='BUY'
};

export enum STATUS {
    ORDER_PLACED='ORDER_PLACED',
    SENT_TO_BINANCE='SENT_TO_BINANCE', 
    SENT_TO_BINANCE_CONFIRMED='SENT_TO_BINANCE', 
    MARKET_ORDER_PLACED='MARKET_ORDER_PLACED', 
    MARKET_ORDER_PENDING='MARKET_ORDER_PENDING', 
    ORDER_FILLED='ORDER_FILLED', 
    SUCCESS='SUCCESS', 
    FAILURE='FAILURE'
};